### ISSUE TITLE
Append to div with class

### ISSUE THREAD

**Issue by avinash-vllbh** [ericaprieto/simply-toast#2]
I was trying to change the appendTo default option for positioning the messages better in my app but it's always appending to body with top offset of 20. Can I make it display in any div that I want,
e.g., 

``` html
<body>
<div class="wrapper">
</div>
</body>
```

I have tried setting, 

``` javascript
'appendTo': "div.wrapper"
'appendTo': ".wrapper" 
```

both doesn't seem to work. Let me know how to go about this.
Also, can I add the default option for offset-right?? The default option only seem to have top!!

**Comment by andreasmueller92** [comment]
Even if I'm 3 and a half years too late, it might help others:

Use id instead of class!
`<body>
<div **id**="wrapper">
</div>
</body>`

And appendTo needs the DOM element:
`'appendTo': document.getElementById('wrapper')`
