### ISSUE TITLE
Stop timer when mousehover

### ISSUE THREAD

**Issue by ncou** [ericaprieto/simply-toast#7]
Hi,

First , very nice plugin.
Is there an option to stop the closing timer when the mouse is over the toast ?

Thank you.

Keep up the good work.

**Comment by ericprieto** [comment]
There's no such option... But if you wait a week, I can help you with that :)

**Comment by ncou** [comment]
good news :)
you make my day.

**Comment by ncou** [comment]
Hi,

any news on this subject ?

Thanks.
